name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

permissions:
  contents: write
  pull-requests: read

jobs:
  call-tests:
    uses: ./.github/workflows/tests.yaml

  create-tags:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: call-tests
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

  releaser:
    if: success()
    needs: create-tags
    uses: ./.github/workflows/goreleaser.yaml
