name: Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Cache Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum')}}
          restore-keys: |
            ${{ runner.os }}-
      - name: Tests
        run: go test -v -coverprofile=coverage.out ./...
      - name: Print Tests
        run: go tool cover -func=coverage.out
